server:
  port: 8085

spring:
  application:
    name: historial-juego

  datasource:
    url: jdbc:mysql://${DB_USER:avnadmin}:${DB_PASSWORD}@torneo-esports-db1-torneo-esports.e.aivencloud.com:20740/defaultdb?ssl-mode=REQUIRED
    username: ${DB_USER:avnadmin}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history_historial
    baseline-version: "0"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: laClaveDeLosEsportsEstanLargaLoSuficiente

usuario-service:
  url: http://usuario

juegos-service:
  url: http://juegos

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
