envVarGroups:
  - name: db-shared
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

services:
  - type: web
    name: christianpastran-torneo-usuario
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./usuario/Dockerfile
    healthCheckPath: /actuator/health
    envVarGroups:
      - db-shared
    envVars:
      - key: EUREKA_ENABLED
        value: false

  - type: web
    name: christianpastran-torneo-auth
    runtime: docker
    plan: free
    dockerContext: ./auth-service
    dockerfilePath: ./auth-service/Dockerfile
    healthCheckPath: /actuator/health
    envVarGroups:
      - db-shared
    envVars:
      - key: EUREKA_ENABLED
        value: false

  - type: web
    name: christianpastran-torneo-gateway
    runtime: docker
    plan: free
    dockerContext: ./getaway-service
    dockerfilePath: ./getaway-service/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false