services:
  - type: web
    name: com-fullstack-auth
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/auth-service.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false

  - type: web
    name: com-fullstack-juegos
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/juegos.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false

  - type: web
    name: com-fullstack-usuario
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/usuario.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false

  - type: web
    name: com-fullstack-torneo
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/torneo.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false

  - type: web
    name: com-fullstack-inscripcion
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/inscripcion-service.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: APP_DISCOVERY_ENABLED
        value: false
      - key: TORNEO_URL
        value: https://com-fullstack-torneo.onrender.com
      - key: USUARIO_URL
        value: https://com-fullstack-usuario.onrender.com
      - key: JUEGOS_URL
        value: https://com-fullstack-juegos.onrender.com

  - type: web
    name: com-fullstack-comentario-torneo
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/comentario-torneo.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: APP_DISCOVERY_ENABLED
        value: false
      - key: TORNEO_URL
        value: https://com-fullstack-torneo.onrender.com
      - key: USUARIO_URL
        value: https://com-fullstack-usuario.onrender.com

  - type: web
    name: com-fullstack-favorito-juego
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/favorito-juego.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: APP_DISCOVERY_ENABLED
        value: false
      - key: USUARIO_URL
        value: https://com-fullstack-usuario.onrender.com
      - key: JUEGOS_URL
        value: https://com-fullstack-juegos.onrender.com

  - type: web
    name: com-fullstack-ficha-partida
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/ficha-partida.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: APP_DISCOVERY_ENABLED
        value: false
      - key: TORNEO_URL
        value: https://com-fullstack-torneo.onrender.com
      - key: USUARIO_URL
        value: https://com-fullstack-usuario.onrender.com
      - key: JUEGOS_URL
        value: https://com-fullstack-juegos.onrender.com

  - type: web
    name: com-fullstack-historial-juego
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/historial-juego.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: APP_DISCOVERY_ENABLED
        value: false
      - key: USUARIO_URL
        value: https://com-fullstack-usuario.onrender.com
      - key: JUEGOS_URL
        value: https://com-fullstack-juegos.onrender.com

  - type: web
    name: com-fullstack-notificacion-usuario
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/notificacion-usuario.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: APP_DISCOVERY_ENABLED
        value: falsem
      - key: USUARIO_URL
        value: https://com-fullstack-usuario.onrender.com

  - type: web
    name: com-fullstack-torneo-patrocinador
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/torneo-patrocinador.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: APP_DISCOVERY_ENABLED
        value: false
      - key: TORNEO_URL
        value: https://com-fullstack-torneo.onrender.com

  - type: web
    name: com-fullstack-gateway
    runtime: docker
    plan: free
    dockerfilePath: ./render/docker/getaway-service.Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: AUTH-SERVICE_URL
        value: https://com-fullstack-auth.onrender.com
      - key: COMENTARIO_TORNEO_URL
        value: https://com-fullstack-comentario-torneo.onrender.com
      - key: FAVORITO_JUEGO_URL
        value: https://com-fullstack-favorito-juego.onrender.com
      - key: FICHA_PARTIDA_URL
        value: https://com-fullstack-ficha-partida.onrender.com
      - key: HISTORIAL_JUEGO_URL
        value: https://com-fullstack-historial-juego.onrender.com
      - key: INSCRIPCION_URL
        value: https://com-fullstack-inscripcion.onrender.com
      - key: JUEGOS_URL
        value: https://com-fullstack-juegos.onrender.com
      - key: NOTIFICACION_USUARIO_URL
        value: https://com-fullstack-notificacion-usuario.onrender.com
      - key: TORNEO_URL
        value: https://com-fullstack-torneo.onrender.com
      - key: USUARIO_URL
        value: https://com-fullstack-usuario.onrender.com
      - key: TORNEO_PATROCINADOR_URL
        value: https://com-fullstack-torneo-patrocinador.onrender.com