services:
  - type: web
    name: christianpastran-torneo-usuario
    runtime: docker
    plan: free
    dockerContext: ./usuario
    dockerfilePath: ./usuario/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_ENABLED
        value: false
      - key: SPRING_DATASOURCE_URL
        value: ${DATABASE_URL_EXTERNAL} # Aquí Render mapeará tu MySQL de la nube
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DATABASE_USER}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DATABASE_PASSWORD}

  # 2. SERVICIO DE AUTENTICACIÓN
  - type: web
    name: christianpastran-torneo-auth
    runtime: docker
    plan: free
    dockerContext: ./auth-service
    dockerfilePath: ./auth-service/Dockerfile # <-- Cambia esto también
    healthCheckPath: /actuator/health

  # 3. API GATEWAY
  - type: web
    name: christianpastran-torneo-gateway
    runtime: docker
    plan: free
    dockerContext: ./getaway-service
    dockerfilePath: ./getaway-service/Dockerfile # <-- Cambia esto también
    healthCheckPath: /actuator/health
    # ...