server:
  port: 8084

spring:
  application:
    name: torneos

  datasource:
    url: jdbc:mysql://avnadmin:AVNS_S9j_LnNsuM8kjeud6wc@torneo-esports-db1-torneo-esports.e.aivencloud.com:20740/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_S9j_LnNsuM8kjeud6wc
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history_torneos
    baseline-version: "0"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: laClaveDeLosEsportsEstanLargaLoSuficiente

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true