server:
  port: ${PORT:8081} # Modificado para que Render le asigne el puerto dinámico[cite: 3]

spring:
  application:
    name: usuario

  datasource:
    # Si detecta la variable de Render usa la de internet, si no, usa la tuya local[cite: 3]
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db-mysql:3306/db_torneo_esports}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history_usuario
    baseline-version: "0"

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: laClaveDeLosEsportsEstanLargaLoSuficiente

eureka:
  client:
    # Desactivamos Eureka en Render usando la pauta del documento[cite: 3]
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

